#pragma once
#include <Arduino.h>
#include "M5Cardputer.h"

enum UIState {
    STATE_MENU,
    STATE_INPUT_F1,
    STATE_INPUT_F2,
    STATE_RESULTS_ACHSEN,
    STATE_INPUT_PUNKTPROBE,
    STATE_RESULTS_GRADKOEFF,
    STATE_RESULTS_SYMMETRIE,
    STATE_RESULTS_EXTREM,
    STATE_RESULTS_WENDEPUNKTE,
    STATE_RESULTS_KRUEMMUNG,
    STATE_RESULTS_MONOTONIE,
    STATE_RESULTS_UNENDLICH,
    STATE_INPUT_TAB_START,
    STATE_INPUT_TAB_END,
    STATE_INPUT_TAB_STEP,
    STATE_RESULTS_TABELLE,
    STATE_PLOT
};

extern UIState currentState;
void Task_TFT(void *pvParameters);